config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from pingdom.urls import urlpatterns as pingdom_urlpatterns

urlpatterns = []

if settings.DEBUG and settings.DJANGO_ENV == "local":
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("", include("users.urls", namespace="users")),
    path("", include("barriers.urls", namespace="barriers")),
    path("", include("reports.urls", namespace="reports")),
    path("", include("core.urls", namespace="core")),
    path("", include("healthcheck.urls", namespace="healthcheck")),
] + pingdom_urlpatterns

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from barriers.views.feedback import FeedbackFormView, FeedbackGratitudeView
from utils.company_search import SearchCompany

app_name = "core"

urlpatterns = [
    path(
        "accessibility/",
        TemplateView.as_view(template_name="accessibility.html"),
        name="accessibility",
    ),
    path(
        "feedback/",
        FeedbackFormView.as_view(),
        name="feedback",
    ),
    path(
        "feedback/thankyou/",
        FeedbackGratitudeView.as_view(),
        name="feedback-thanks",
    ),
    path(
        "companies/search/<str:search_term>/",
        SearchCompany.as_view(),
        name="search_company",
    ),
]

users/urls.py
from django.urls import path

from users.account.views import (
    UserEditBarrierLocations,
    UserEditGovernmentDepartment,
    UserEditOverseasRegions,
    UserEditPolicyTeams,
    UserEditSectors,
)
from users.views import (
    Account,
    AccountDownloads,
    AccountDrafts,
    AccountSavedSearch,
    AddUser,
    DeleteUser,
    EditUser,
    ExportUsers,
    GetUsers,
    Login,
    LoginCallback,
    ManageUsers,
    Mentions,
    SignOut,
    UserDetail,
)

app_name = "users"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("login/callback/", LoginCallback.as_view(), name="login_callback"),
    path("sign-out/", SignOut.as_view(), name="sign-out"),
    path("users/", ManageUsers.as_view(), name="manage_users"),
    path("users/search/", GetUsers.as_view(), name="get_users"),
    path("users/export/", ExportUsers.as_view(), name="export_users"),
    path("users/add/", AddUser.as_view(), name="add_user"),
    path("users/<int:user_id>/", UserDetail.as_view(), name="user_detail"),
    path("users/<int:user_id>/edit/", EditUser.as_view(), name="edit_user"),
    path("users/<int:user_id>/delete/", DeleteUser.as_view(), name="delete_user"),
    path("account/", Account.as_view(), name="account"),
    path(
        "account/saved_searches/",
        AccountSavedSearch.as_view(),
        name="account_saved_searches",
    ),
    path(
        "account/downloads/",
        AccountDownloads.as_view(),
        name="account_downloads",
    ),
    path(
        "account/drafts/",
        AccountDrafts.as_view(),
        name="account_drafts",
    ),
    path(
        "account/policy-teams/edit/",
        UserEditPolicyTeams.as_view(),
        name="edit_user_policy_teams",
    ),
    path(
        "account/sectors/edit/",
        UserEditSectors.as_view(),
        name="edit_user_sectors",
    ),
    path(
        "account/barrier-locations/edit/",
        UserEditBarrierLocations.as_view(),
        name="edit_user_barrier_locations",
    ),
    path(
        "account/overseas-regions/edit/",
        UserEditOverseasRegions.as_view(),
        name="edit_user_overseas_regions",
    ),
    path(
        "account/government-department/edit/",
        UserEditGovernmentDepartment.as_view(),
        name="edit_user_government_department",
    ),
    path("mentions/", Mentions.as_view(), name="mentions"),
]

users/models.py
from utils.models import APIModel

from .datahub import get_visible_apps


class Group(APIModel):
    @property
    def plural_name(self):
        if "Regional Lead" not in self.name and "Related Barriers" not in self.name:
            return f"{self.name}s"
        else:
            return self.name


class DashboardTask(APIModel):
    def to_dict(self):
        return {
            "barrier_code": self.barrier_code,
            "barrier_title": self.barrier_title,
            "message": self.message,
            "tag": self.tag,
        }


class User(APIModel):
    _apps = None

    @property
    def groups_display(self):
        group_names = [group["name"] for group in self.data.get("groups")]
        if group_names:
            return ", ".join(group_names)
        return "General user"

    @property
    def permitted_applications(self):
        return self.data.get("permitted_applications", [])

    @property
    def permissions(self):
        return self.data.get("permissions", [])

    def has_permission(self, permission_name):
        if not self.is_active:
            return False
        return self.is_superuser or permission_name in self.permissions

    def get_apps(self):
        return get_visible_apps(self)

    @property
    def apps(self):
        if self._apps is None:
            self._apps = self.get_apps()
        return self._apps

    @property
    def has_crm_permission(self):
        for app in self.apps:
            if app["permittedKey"] == "datahub-crm":
                return True
        return False

    @property
    def has_approved_digital_trade_email(self):
        return self.data.get("has_approved_digital_trade_email", False)

    @property
    def initials(self):
        first_name = self.data.get("first_name")
        last_name = self.data.get("last_name")
        if first_name:
            if last_name:
                return first_name[0] + last_name[0]
            return first_name[0]
        return "U"


class UserProfile(APIModel):
    pass

users/account/forms.py
import json

from django import forms


class UserEditBaseForm(forms.Form):

    def clean(self):
        cleaned_data = super().clean()
        cleaned_list = []
        if cleaned_data["form"]:
            cleaned_list = json.loads(cleaned_data["form"])
        if isinstance(cleaned_list, list):
            cleaned_data["form"] = cleaned_list
        else:
            cleaned_data["form"] = [cleaned_list]


class UserEditPolicyTeamsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Policy teams",
        help_text="Add policy teams to keep track on the policy areas which affect the barriers you’ve working on, "
        "or to stay connected with colleagues you work with or manage. ",
    )


class UserEditSectorsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Sectors",
    )


class UserEditBarrierLocationsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Barrier locations",
        help_text="All the barrier locations you're interested in by selecting them from the dropdown list. "
        "Or type the first few letters of the location name into the box.",
    )


class UserEditOverseasRegionsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Overseas regions",
    )


class UserEditGovernmentDepartmentForm(UserEditBaseForm):
    form = forms.ChoiceField(
        required=False,
        label="Government department",
        help_text="Add Government departments to stay connected with colleagues outside of the Department of "
        "Business and Trade, who are working on the barriers you’re trying to resolve.",
    )

    def __init__(self, select_options, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["form"].choices = select_options

users/forms.py
import logging

from django import forms
from django.conf import settings

from barriers.forms.mixins import APIFormMixin
from users.constants import (
    REGIONAL_LEAD_PERMISSION_GROUPS,
    USER_ADDITIONAL_PERMISSION_GROUPS,
)
from utils.api.client import MarketAccessAPIClient

logger = logging.getLogger(__name__)


class UserSearchForm(forms.Form):
    query = forms.CharField(
        label="Find a user to add",
        max_length=255,
        required=False,
    )


class UserGroupForm(APIFormMixin, forms.Form):
    group = forms.ChoiceField(
        label="Role",
        choices=[("0", "General user")],
        error_messages={"required": "Select a role"},
    )
    additional_permissions = forms.MultipleChoiceField(
        label="Permissions",
        choices=[],
        required=False,
    )
    regional_lead_groups = forms.MultipleChoiceField(
        label="Regional Leader Assignment",
        choices=[],
        required=False,
    )

    def __init__(self, groups, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 2 Types of group in the groups list; roles and additional permissions
        # users should only have one role, but can belong to multiple addition permission groups.
        # Add group to the radio button group select if it is a 'role'
        # Add group to the checkbox group select if it is an 'additional permission'
        # Regional Leader permission groups are seperated so only admins can assign users

        for group in groups:
            if group.name == "Role administrator":
                if settings.DISPLAY_ROLE_ADMIN_GROUP:
                    self.fields["additional_permissions"].choices.append(
                        (str(group.id), group.name)
                    )
            elif group.name in USER_ADDITIONAL_PERMISSION_GROUPS:
                self.fields["additional_permissions"].choices.append(
                    (str(group.id), group.name)
                )
            elif group.name in REGIONAL_LEAD_PERMISSION_GROUPS:
                self.fields["regional_lead_groups"].choices.append(
                    (str(group.id), group.name)
                )
            else:
                self.fields["group"].choices.append((str(group.id), group.name))

    def save(self):
        client = MarketAccessAPIClient(self.token)

        # Groups/roles list
        if self.cleaned_data.get("group") == "0":
            groups = []
        else:
            groups = [{"id": self.cleaned_data["group"]}]

        # Additional permissions
        selected_permissions = self.cleaned_data.get("additional_permissions")
        for added_permission in selected_permissions:
            groups.append({"id": added_permission})

        # Regional leader assignment
        regions_selected = self.cleaned_data.get("regional_lead_groups")
        for region_lead_permission in regions_selected:
            groups.append({"id": region_lead_permission})

        client.users.patch(id=self.id, groups=groups)


class UserDeleteForm(APIFormMixin, forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.id_to_delete = kwargs["id"]

    def save(self):
        client = MarketAccessAPIClient(self.token)
        client.users.patch(id=self.id_to_delete, is_active=False, groups=[])

users/account/views.py
import json

from django.urls import reverse
from django.views.generic import FormView, TemplateView

from users.account.forms import (
    UserEditBarrierLocationsForm,
    UserEditGovernmentDepartmentForm,
    UserEditOverseasRegionsForm,
    UserEditPolicyTeamsForm,
    UserEditSectorsForm,
)
from utils.api.client import MarketAccessAPIClient
from utils.metadata import MetadataMixin


class UserEditBase(FormView, TemplateView, MetadataMixin):

    def get_initial_ids(self, area, id_type="id"):
        self.client = MarketAccessAPIClient(self.request.session.get("sso_token"))
        self.current_user = self.client.users.get_current()
        return [
            item[id_type]
            for item in self.client.profile.get(id=self.current_user.id).data[area]
        ]

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(
            {
                "page": "account",
            }
        )
        return context_data

    def patch_to_api(self, form, area):
        patch_args = {
            "id": str(self.current_user.id),
            area: sorted(form.cleaned_data["form"]),
        }
        self.client.profile.patch(**patch_args)

    def get_success_url(self):
        return reverse(
            "users:account",
        )


class UserEditPolicyTeams(UserEditBase):
    template_name = "users/account/edit_policy_teams.html"
    form_class = UserEditPolicyTeamsForm

    def get_initial(self):
        return {"form": self.get_initial_ids("policy_teams")}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(
            {
                "select_options": [
                    (policy_team["id"], policy_team["title"])
                    for policy_team in self.metadata.get_policy_team_list()
                ]
            }
        )
        return context_data

    def form_valid(self, form):
        self.patch_to_api(form, "policy_teams")
        return super().form_valid(form)


class UserEditSectors(UserEditBase):
    template_name = "users/account/edit_sectors.html"
    form_class = UserEditSectorsForm

    def get_initial(self):
        return {"form": json.dumps(self.get_initial_ids("sectors"))}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(
            {
                "select_options": [
                    (sector["id"], sector["name"])
                    for sector in self.metadata.get_sector_list(level=0)
                ]
            }
        )
        return context_data

    def form_valid(self, form):
        self.patch_to_api(form, "sectors")
        return super().form_valid(form)


class UserEditOverseasRegions(UserEditBase):
    template_name = "users/account/edit_overseas_regions.html"
    form_class = UserEditOverseasRegionsForm

    def get_initial(self):
        return {"form": json.dumps(self.get_initial_ids("overseas_regions"))}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(
            {"select_options": self.metadata.get_overseas_region_choices()}
        )
        return context_data

    def form_valid(self, form):
        self.patch_to_api(form, "overseas_regions")
        return super().form_valid(form)


class UserEditBarrierLocations(UserEditBase):
    template_name = "users/account/edit_barrier_locations.html"
    form_class = UserEditBarrierLocationsForm

    def get_initial(self):
        trading_blocs = self.get_initial_ids("trading_blocs", "code")
        countries = self.get_initial_ids("countries")
        return {
            "form": json.dumps(trading_blocs + countries),
        }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        locations = (
            (
                "Trading blocs",
                (
                    [
                        (bloc["code"], bloc["name"])
                        for bloc in self.metadata.get_trading_bloc_list()
                    ]
                ),
            ),
            (
                "Countries",
                (
                    [
                        (country["id"], country["name"])
                        for country in self.metadata.get_country_list()
                    ]
                ),
            ),
        )
        context_data.update({"select_options": locations})
        return context_data

    def form_valid(self, form):
        countries = []
        trading_blocs = []
        for location in form.cleaned_data["form"]:
            if self.metadata.is_trading_bloc_code(location):
                trading_blocs.append(location)
            else:
                countries.append(location)
        self.client.profile.patch(
            id=str(self.current_user.id),
            trading_blocs=sorted(trading_blocs),
            countries=sorted(countries),
        )
        return super().form_valid(form)


class UserEditGovernmentDepartment(UserEditBase):
    template_name = "users/account/edit_government_department.html"
    form_class = UserEditGovernmentDepartmentForm

    def get_form_kwargs(self):
        self.client = MarketAccessAPIClient(self.request.session.get("sso_token"))
        self.current_user = self.client.users.get_current()
        kwargs = super().get_form_kwargs()
        kwargs["select_options"] = self.metadata.get_gov_organisation_choices()
        return kwargs

    def form_valid(self, form):
        self.patch_to_api(form, "organisations")
        return super().form_valid(form)

templates/users/partials/user_search_form.html
<form action="" method="POST" role="search" class="search-form">
    {% csrf_token %}

    <div id="{{ form.query.name }}" class="govuk-form-group">
        <label class="govuk-label govuk-!-font-size-19 govuk-!-font-weight-bold" for="user">
            {% if query_label %}{{ query_label }}{% else %}{{ form.query.label }}{% endif %}
        </label>

        <span id="user-hint" class="govuk-hint">
        </span>

        {% form_field_error form "query" %}

        <div class="search-form__input-group">
            <input
                class="govuk-input search-form__input{% if form.query.error %} govuk-input--error{% endif %}"
                id="user"
                name="query"
                type="text"
                value="{% if form.query.value %}{{ form.query.value }}{% endif %}"
                placeholder="Search for user"
                {% if not form.query.value and not form.query.error %}autofocus{% endif %}
                aria-describedby="user-hint"
            >
        </div>
    </div>

    <button type="submit" class="search-form__button govuk-button">Search</button>
    {% if cancel_url %}<a href="{{ cancel_url }}" class="form-cancel">Cancel</a>{% endif %}
</form>

{% if error %}
    <p class="error-message">{{ error }}</p>
{% endif %}

{% if form.is_valid %}
    <h2 class="results-count" role="alert">
        <span class="results-count__number">{{ results|length }}</span>
        users match <span class="highlight">{{ form.query.value }}</span>
    </h2>
{% endif %}

templates/users/partials/user_search_results.html
{% load highlight %}

{% if results %}
    <ul class="search-card-list">
        {% for user in results %}
            {% if user.link %}
                <li class="search-card">
                    <a href="{{ user.link }}">{{ user.first_name|highlight:form.query.value }} {{ user.last_name|highlight:form.query.value }}</a>
                </li>
            {% else %}
                <li class="search-card">
                    <form action="" method="POST" class="add-form">
                        {% csrf_token %}
                        <input name="query" id="query" value="{{ form.query.value }}" hidden aria-hidden="true">
                        <input name="user_id" id="add_user_id" value="{{ user.user_id }}" hidden aria-hidden="true">
                        <input name="user_full_name" id="add_user_full_name" value="{{ user.first_name }} {{ user.last_name }}" hidden aria-hidden="true">
                        <button type="submit" name="action" value="add" class="search-card__button">
                            <h3 class="search-card__heading">Add {{ user.first_name|highlight:form.query.value }} {{ user.last_name|highlight:form.query.value }}</h3>
                        </button>
                    </form>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endif %}

templates/users/partials/usergroup_selection.html
<div class="govuk-form-group">
    <label class="govuk-label" for="filter_group">
        Filter by group
    </label>
    <select class="govuk-select" id="filter_group" name="group">
        <option value="all">All users</option>
        {% for group in groups %}
            <option value="{{ group.id }}"{% if group_id == group.id %} selected{% endif %}>
                {{ group.plural_name}}
            </option>
        {% endfor %}
    </select>
    <button class="govuk-button dmas-js-disabled-button" type="submit" value="Filter">
        Filter
    </button>
</div>

{#<ul class="page-tabs page-tabs--no-margin">#}
{#    {% if group_id %}#}
{#        <li class="page-tabs__tab">#}
{#            <a class="page-tabs__tab__text" href="{% url 'users:manage_users' %}">All users</a>#}
{#        </li>#}
{#    {% else %}#}
{#        <li class="page-tabs__tab page-tabs__tab--active">#}
{#            <span class="page-tabs__tab__text">All users</span>#}
{#        </li>#}
{#    {% endif %}#}
{##}
{#    {% for group in groups %}#}
{#        {% if group_id == group.id %}#}
{#            <li class="page-tabs__tab page-tabs__tab--active">#}
{#                <span class="page-tabs__tab__text">{{ group.plural_name }}</span>#}
{#            </li>#}
{#        {% else %}#}
{#            <li class="page-tabs__tab">#}
{#                <a class="page-tabs__tab__text" href="?group={{ group.id }}">{{ group.plural_name }}</a>#}
{#            </li>#}
{#        {% endif %}#}
{#    {% endfor %}#}
{#</ul>#}