barriers/urls.py
from django.urls import path, re_path

from barriers.views.action_plans import (
    ActionPlanMilestoneFormView,
    ActionPlanRisksAndMitigationView,
    ActionPlanStakeholdersListView,
    ActionPlanTaskCompletionDateChangeFormView,
    ActionPlanTaskFormView,
    ActionPlanTemplateView,
    AddActionPlanStrategicContext,
    CreateActionPlanStakeholderIndividualFormView,
    CreateActionPlanStakeholderOrganisationFormView,
    CreateActionPlanStakeholderTypeFormView,
    DeleteActionPlanMilestoneView,
    DeleteActionPlanTaskView,
    EditActionPlanCurrentStatusFormView,
    EditActionPlanOwner,
    EditActionPlanStakeholderDetailsFormView,
    EditActionPlanTaskOutcomeFormView,
    EditActionPlanTaskProgressFormView,
    RemoveActionPlanOwner,
    SelectActionPlanOwner,
)
from barriers.views.archive import ArchiveBarrier, UnarchiveBarrier
from barriers.views.assessments.economic import (
    AddEconomicAssessment,
    AddEconomicAssessmentDocument,
    ArchiveEconomicAssessment,
    AutomateEconomicAssessment,
    CancelEconomicAssessmentDocument,
    DeleteEconomicAssessmentDocument,
    EconomicAssessmentDetail,
    EconomicAssessmentRawData,
    EditEconomicAssessmentRating,
)
from barriers.views.assessments.economic_impact import (
    AddEconomicImpactAssessment,
    ArchiveEconomicImpactAssessment,
    EconomicImpactAssessmentDetail,
)
from barriers.views.assessments.overview import AssessmentOverview
from barriers.views.assessments.preliminary_assessment import PreliminaryAssessmentValue
from barriers.views.assessments.resolvability import (
    AddResolvabilityAssessment,
    ArchiveResolvabilityAssessment,
    EditResolvabilityAssessment,
    ResolvabilityAssessmentDetail,
)
from barriers.views.assessments.strategic import (
    AddStrategicAssessment,
    ArchiveStrategicAssessment,
    EditStrategicAssessment,
    StrategicAssessmentDetail,
)
from barriers.views.commodities import BarrierEditCommodities
from barriers.views.companies import (
    BarrierEditCompanies,
    BarrierEditCompaniesSession,
    BarrierRemoveCompany,
    CompanyDetail,
)
from barriers.views.documents import DownloadDocument
from barriers.views.edit import (
    BarrierEditCausedByTradingBloc,
    BarrierEditCommercialValue,
    BarrierEditEconomicAssessmentEligibility,
    BarrierEditEstimatedResolutionDateConfirmationPage,
    BarrierEditPriority,
    BarrierEditProduct,
    BarrierEditStartDate,
    BarrierEditSummary,
    BarrierEditTags,
    BarrierEditTitle,
    BarrierEditTradeDirection,
)
from barriers.views.export_types import BarrierEditExportType
from barriers.views.government_organisations import (
    BarrierAddGovernmentOrganisation,
    BarrierEditGovernmentOrganisations,
    BarrierRemoveGovernmentOrganisation,
)
from barriers.views.history import BarrierHistory
from barriers.views.location import (
    AddAdminArea,
    BarrierEditCountryOrTradingBloc,
    BarrierEditLocation,
    BarrierEditLocationSession,
    RemoveAdminArea,
)
from barriers.views.mentions import (
    MentionMarkAllAsRead,
    MentionMarkAllAsUnread,
    MentionMarkAsRead,
    MentionMarkAsReadAndRedirect,
    MentionMarkAsUnread,
    TurnNotificationsOffAndRedirect,
    TurnNotificationsOnAndRedirect,
)
from barriers.views.notes import (
    AddNoteDocument,
    BarrierAddNote,
    BarrierDeleteNote,
    BarrierEditNote,
    CancelNoteDocument,
    DeleteNoteDocument,
)
from barriers.views.policy_teams import (
    AddPolicyTeam,
    BarrierEditPolicyTeams,
    BarrierEditPolicyTeamsSession,
    BarrierRemovePolicyTeam,
)
from barriers.views.progress_updates import (
    BarrierAddProgrammeFundProgressUpdate,
    BarrierAddProgressUpdate,
    BarrierCompleteNextStepItem,
    BarrierEditNextStepItem,
    BarrierEditProgressUpdate,
    BarrierListNextStepsItems,
    BarrierListProgressUpdate,
    ChooseProgressUpdateTypeView,
    ProgrammeFundEditProgressUpdate,
    ProgrammeFundListProgressUpdate,
)
from barriers.views.public_barriers import (
    EditPublicEligibility,
    EditPublicSummary,
    EditPublicTitle,
    PublicBarrierApprovalConfirmation,
    PublicBarrierDetail,
    PublicBarrierListView,
    PublicBarrierPublishConfirmation,
    PublicBarrierUnpublishConfirmation,
)
from barriers.views.saved_searches import (
    DeleteSavedSearch,
    NewSavedSearch,
    RenameSavedSearch,
    SavedSearchNotifications,
)
from barriers.views.search import (
    BarrierDownloadLink,
    BarrierSearch,
    DownloadBarriers,
    DownloadBarriersDelete,
    DownloadBarriersDetail,
    RequestBarrierDownloadApproval,
)
from barriers.views.sectors import (
    BarrierAddAllSectors,
    BarrierAddMainSector,
    BarrierAddSectors,
    BarrierEditSectors,
    BarrierEditSectorsSession,
    BarrierRemoveSector,
)
from barriers.views.statuses import BarrierChangeStatus
from barriers.views.teams import (
    BarrierTeam,
    ChangeOwnerView,
    DeleteTeamMember,
    SearchTeamMember,
)
from barriers.views.wto import (
    AddWTODocument,
    CancelWTODocuments,
    DeleteWTODocument,
    EditWTOProfile,
    EditWTOStatus,
)

from .views.core import (
    BarrierDetail,
    Dashboard,
    GetDashboardSummary,
    Home,
    WhatIsABarrier,
)
from .views.estimated_resolution_date import AddEstimatedResolutionDateFormView, EditEstimatedResolutionDateFormView, \
    DeleteEstimatedResolutionDateFormView, ReviewEstimatedResolutionDateFormView, RejectEstimatedResolutionDateFormView, \
    ApproveEstimatedResolutionDateFormView, ConfirmationEstimatedResolutionDateFormView
from .views.related_barriers import RelatedBarriers

app_name = "barriers"

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
    path("search/", BarrierSearch.as_view(), name="search"),
    path("find-a-barrier/", BarrierSearch.as_view(), name="find_a_barrier"),
    path("search/download/", DownloadBarriers.as_view(), name="download"),
    path(
        "search/download/<uuid:download_barrier_id>",
        DownloadBarriersDetail.as_view(),
        name="download-detail",
    ),
    path(
        "search/download/<uuid:download_barrier_id>/link/",
        BarrierDownloadLink.as_view(),
        name="download-link",
    ),
    path(
        "search/download/<uuid:download_barrier_id>/delete/",
        DownloadBarriersDelete.as_view(),
        name="delete-download",
    ),
    path(
        "search/request_download_approval/",
        RequestBarrierDownloadApproval.as_view(),
        name="request_download_approval",
    ),
    path("what-is-a-barrier/", WhatIsABarrier.as_view(), name="what_is_a_barrier"),
    path(
        "documents/<uuid:document_id>/download/",
        DownloadDocument.as_view(),
        name="download_document",
    ),
    path("saved-searches/new/", NewSavedSearch.as_view(), name="new_saved_search"),
    path(
        "saved-searches/<uuid:saved_search_id>/rename/",
        RenameSavedSearch.as_view(),
        name="rename_saved_search",
    ),
    path(
        "saved-searches/<uuid:saved_search_id>/delete/",
        DeleteSavedSearch.as_view(),
        name="delete_saved_search",
    ),
    path(
        "saved-searches/<uuid:saved_search_id>/notifications/",
        SavedSearchNotifications.as_view(),
        name="saved_search_notifications",
    ),
    re_path(
        "saved-searches/(?P<saved_search_id>(my|team)-barriers)/notifications/",
        SavedSearchNotifications.as_view(),
        name="saved_search_notifications",
    ),
    path("barriers/<uuid:barrier_id>/", BarrierDetail.as_view(), name="barrier_detail"),
    # Reason for double url: Analytics requested a second url pointing to the same page
    path(
        "barriers/<uuid:barrier_id>/complete/",
        BarrierDetail.as_view(),
        name="barrier_detail_from_complete",
    ),
    re_path(
        "barriers/(?P<barrier_id>[A-Z]-[0-9]{2}-[A-Z0-9]{3})/",
        BarrierDetail.as_view(),
        name="barrier_detail_by_code",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/title/",
        BarrierEditTitle.as_view(),
        name="edit_title",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/product/",
        BarrierEditProduct.as_view(),
        name="edit_product",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/summary/",
        BarrierEditSummary.as_view(),
        name="edit_summary",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/priority/",
        BarrierEditPriority.as_view(),
        name="edit_priority",
    ),
    path(
        "barriers/<uuid:barrier_id>/list/progress_update/",
        BarrierListProgressUpdate.as_view(),
        name="list_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/progress_update/<uuid:progress_update_id>/",
        BarrierEditProgressUpdate.as_view(),
        name="edit_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/list/programme_fund_progress_update/",
        ProgrammeFundListProgressUpdate.as_view(),
        name="list_barrier_fund_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/programme_fund_progress_update/<uuid:progress_update_id>/",
        ProgrammeFundEditProgressUpdate.as_view(),
        name="edit_barrier_fund_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/list/next_steps_items/",
        BarrierListNextStepsItems.as_view(),
        name="list_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/next_step_item_update/<uuid:item_id>/",
        BarrierEditNextStepItem.as_view(),
        name="edit_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/add/next_step_item_update/",
        BarrierEditNextStepItem.as_view(),
        name="add_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/next_step_item_complete/<uuid:item_id>/",
        BarrierCompleteNextStepItem.as_view(),
        name="complete_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/economic-assessment-eligibility/",

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from pingdom.urls import urlpatterns as pingdom_urlpatterns

urlpatterns = []

if settings.DEBUG and settings.DJANGO_ENV == "local":
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("", include("users.urls", namespace="users")),
    path("", include("barriers.urls", namespace="barriers")),
    path("", include("reports.urls", namespace="reports")),
    path("", include("core.urls", namespace="core")),
    path("", include("healthcheck.urls", namespace="healthcheck")),
] + pingdom_urlpatterns

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from barriers.views.feedback import FeedbackFormView, FeedbackGratitudeView
from utils.company_search import SearchCompany

app_name = "core"

urlpatterns = [
    path(
        "accessibility/",
        TemplateView.as_view(template_name="accessibility.html"),
        name="accessibility",
    ),
    path(
        "feedback/",
        FeedbackFormView.as_view(),
        name="feedback",
    ),
    path(
        "feedback/thankyou/",
        FeedbackGratitudeView.as_view(),
        name="feedback-thanks",
    ),
    path(
        "companies/search/<str:search_term>/",
        SearchCompany.as_view(),
        name="search_company",
    ),
]

reports/urls.py
from django.urls import path

from reports.report_barrier_view import ReportBarrierWizardView
from reports.views import DeleteReport, DraftBarriers, NewReport

app_name = "reports"

urlpatterns = [
    # Two routes into form - one provides a barrier_id (if the draft already exists), one where
    # we make a new 'report' object in the DB
    path("reports/new", NewReport.as_view(), name="new_report"),
    path(
        "reports/start",
        ReportBarrierWizardView.as_view(url_name="reports:report-barrier-wizard-step"),
        name="report-barrier-wizard",
    ),
    path(
        "reports/<str:step>",
        ReportBarrierWizardView.as_view(url_name="reports:report-barrier-wizard-step"),
        name="report-barrier-wizard-step",
    ),
    path(
        "reports/drafts/<uuid:draft_barrier_id>",
        ReportBarrierWizardView.as_view(url_name="reports:report-barrier-wizard-step"),
        name="report-barrier-drafts",
    ),
    path("draft-barriers", DraftBarriers.as_view(), name="draft_barriers"),
    path(
        "reports/<uuid:barrier_id>/delete",
        DeleteReport.as_view(),
        name="delete_report",
    ),
]

users/urls.py
from django.urls import path

from users.account.views import (
    UserEditBarrierLocations,
    UserEditGovernmentDepartment,
    UserEditOverseasRegions,
    UserEditPolicyTeams,
    UserEditSectors,
)
from users.views import (
    Account,
    AccountDownloads,
    AccountDrafts,
    AccountSavedSearch,
    AddUser,
    DeleteUser,
    EditUser,
    ExportUsers,
    GetUsers,
    Login,
    LoginCallback,
    ManageUsers,
    Mentions,
    SignOut,
    UserDetail,
)

app_name = "users"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("login/callback/", LoginCallback.as_view(), name="login_callback"),
    path("sign-out/", SignOut.as_view(), name="sign-out"),
    path("users/", ManageUsers.as_view(), name="manage_users"),
    path("users/search/", GetUsers.as_view(), name="get_users"),
    path("users/export/", ExportUsers.as_view(), name="export_users"),
    path("users/add/", AddUser.as_view(), name="add_user"),
    path("users/<int:user_id>/", UserDetail.as_view(), name="user_detail"),
    path("users/<int:user_id>/edit/", EditUser.as_view(), name="edit_user"),
    path("users/<int:user_id>/delete/", DeleteUser.as_view(), name="delete_user"),
    path("account/", Account.as_view(), name="account"),
    path(
        "account/saved_searches/",
        AccountSavedSearch.as_view(),
        name="account_saved_searches",
    ),
    path(
        "account/downloads/",
        AccountDownloads.as_view(),
        name="account_downloads",
    ),
    path(
        "account/drafts/",
        AccountDrafts.as_view(),
        name="account_drafts",
    ),
    path(
        "account/policy-teams/edit/",
        UserEditPolicyTeams.as_view(),
        name="edit_user_policy_teams",
    ),
    path(
        "account/sectors/edit/",
        UserEditSectors.as_view(),
        name="edit_user_sectors",
    ),
    path(
        "account/barrier-locations/edit/",
        UserEditBarrierLocations.as_view(),
        name="edit_user_barrier_locations",
    ),
    path(
        "account/overseas-regions/edit/",
        UserEditOverseasRegions.as_view(),
        name="edit_user_overseas_regions",
    ),
    path(
        "account/government-department/edit/",
        UserEditGovernmentDepartment.as_view(),
        name="edit_user_government_department",
    ),
    path("mentions/", Mentions.as_view(), name="mentions"),
]

users/account/forms.py
import json

from django import forms


class UserEditBaseForm(forms.Form):

    def clean(self):
        cleaned_data = super().clean()
        cleaned_list = []
        if cleaned_data["form"]:
            cleaned_list = json.loads(cleaned_data["form"])
        if isinstance(cleaned_list, list):
            cleaned_data["form"] = cleaned_list
        else:
            cleaned_data["form"] = [cleaned_list]


class UserEditPolicyTeamsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Policy teams",
        help_text="Add policy teams to keep track on the policy areas which affect the barriers you’ve working on, "
        "or to stay connected with colleagues you work with or manage. ",
    )


class UserEditSectorsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Sectors",
    )


class UserEditBarrierLocationsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Barrier locations",
        help_text="All the barrier locations you're interested in by selecting them from the dropdown list. "
        "Or type the first few letters of the location name into the box.",
    )


class UserEditOverseasRegionsForm(UserEditBaseForm):
    form = forms.CharField(
        required=False,
        label="Overseas regions",
    )


class UserEditGovernmentDepartmentForm(UserEditBaseForm):
    form = forms.ChoiceField(
        required=False,
        label="Government department",
        help_text="Add Government departments to stay connected with colleagues outside of the Department of "
        "Business and Trade, who are working on the barriers you’re trying to resolve.",
    )

    def __init__(self, select_options, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["form"].choices = select_options

templates/users/account/account.html
{% extends "base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% block page_title %}
    {{ block.super }} - Account
{% endblock page_title %}
{% block masthead %}
    {% include "users/partials/account/banner.html" with active=active %}
{% endblock masthead %}
{% block page_content %}
    <section class="govuk-grid-row">
        <div class="govuk-grid-column-full">{% include "users/partials/account/my_profile.html" %}</div>
    </section>
    <section class="govuk-grid-row">
        <div class="govuk-grid-column-full">{% include "users/partials/account/my_role_and_areas_of_interest.html" %}</div>
    </section>
{% endblock page_content %}

templates/users/account/downloads.html
{% extends "base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% block page_title %}
    {{ block.super }} - Account
{% endblock page_title %}
{% block masthead %}
    {% include "users/partials/account/banner.html" with active=active %}
{% endblock masthead %}
{% block page_content %}
    <section>
        <h2 class="ma-list-heading">
            <span class="ma-list-heading__count">{{ barrier_downloads|length }}</span> download{{ barrier_downloads|length|pluralize:"s" }}
        </h2>
        {% if barrier_downloads|length == 0 %}
            <p>You have no downloads</p>
            <p>
                <a href="https://data-services-help.trade.gov.uk/market-access/how-guides/download-barrier-details-spreadsheet/">How do I download barriers?</a>
            </p>
        {% else %}
            <details class="govuk-details">
                <summary class="govuk-details__summary">
                    <span class="govuk-details__summary-text">Acceptable use agreement</span>
                </summary>
                <div class="govuk-details__text">
                    <p class="govuk-body">
                        In order to download market access information from the Digital Market Access System (DMAS), you agree that:
                    </p>
                    <ul class="govuk-list govuk-list--bullet">
                        <li>the downloaded information is commercially sensitive and may contain personal data</li>
                        <li>
                            when handling market access information you will follow your organisation’s information security and data protection policies
                        </li>
                        <li>
                            any information security breach involving the downloaded information will be reported to your Data Protection team without undue delay
                        </li>
                        <li>
                            the downloaded market access information shall be used solely for the purpose of resolving market access barriers and will not be shared publicly without consultation with the Department for Business and Trade (DBT), which remains the Data Owner
                        </li>
                    </ul>
                    DMAS user privacy notice
                    <br>
                    <p class="govuk-body">
                        View information about how your personal data is processed when you use DMAS <a href="https://data-services-help.trade.gov.uk/market-access/about-barriers-and-market-access/digital-market-access-service-dmas-privacy-notice/"
                                                                                                        class="govuk-link"
                                                                                                        target="_blank">here (opens in new tab)</a>
                    </p>
                </div>
            </details>
            <ul class="ma-card-list">
                {% for download in barrier_downloads %}
                    <li class="ma-card-list__item barrier-download">
                        <div class="barrier-download__content">
                            <div class="barrier-download__content--item">
                                <h3 class="barrier-download__title">
                                    {% if download.status == "Complete" %}
                                        <a href="{% url 'barriers:download-link' download.id %}"
                                           aria-label="Download C S V results for ">{{ download.name }}</a>
                                    {% else %}
                                        {{ barrier_download.name }}
                                    {% endif %}
                                </h3>
                                <p>{{ download.count }} result{{ download.count|length|pluralize:"s" }}</p>
                                {% if download.filters %}
                                    <ul class="barrier-download__filter-list">
                                        {% for name, value in download.readable_filters.items %}
                                            <li class="barrier-download__filter-list-item">{{ value.readable_value|striptags }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                            <div class="barrier-download__content--item">
                                <p>
                                    Download status: <span class="title">{{ download.status }}</span>
                                </p>
                                <p class="time-item">Requested {{ download.created_on|timesince }} ago</p>
                                {% if download.status == "Complete" %}
                                    {# no action #}
                                {% elif download.status == "Failed" %}
                                    <p>Download failed</p>
                                {% else %}
                                    <p>We're working on your download. Refresh this page</p>
                                {% endif %}
                            </div>
                            <div class="barrier-download__content--item">
                                <a class="action"
                                   href="{% url 'barriers:delete-download' download.id %}">Delete</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>
{% endblock page_content %}

templates/users/account/drafts.html
{% extends "base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% block page_title %}
    {{ block.super }} - Account
{% endblock page_title %}
{% block masthead %}
    {% include "users/partials/account/banner.html" with active=active %}
{% endblock masthead %}
{% block page_content %}

    <h2 class="ma-list-heading"><span class="ma-list-heading__count">{{ reports|length }}</span> draft barrier{{ reports|pluralize }}</h2>

    {% if reports %}

        <table class="standard-table my-draft-barriers">
            <thead>
                <tr class="standard-table__heading-row">
                    <th class="standard-table__heading standard-table__heading--active">Date started</th>
                    <th class="standard-table__heading">Barrier ID</th>
                    <th class="standard-table__heading">Barrier location</th>
                    <th class="standard-table__heading">Resolved?</th>
                    <th class="standard-table__heading">Barrier title</th>
                    <th class="standard-table__heading">Started by</th>
                    <th class="standard-table__heading">Action</th>
                </tr>
            </thead>
            <tbody class="js-delete-modal-container">
                {% for report in reports %}
                    <tr class="standard-table__row draft-barrier-item">
                        <td class="standard-table__cell">
                            {% if report.created_on %}{{ report.created_on|date:"j F Y" }} at {{ report.created_on|date:"g:iA"|lower }}{% else %}---{% endif %}
                        </td>
                        <td class="standard-table__cell">
                            {{ report.code }}
                        </td>
                        <td class="standard-table__cell">
                            {% if report.country %}
                                {{ report.country.name|default:'---' }}
                            {% else %}
                                {{ report.trading_bloc.name|default:'---' }}
                            {% endif %}
                        </td>
                        <td class="standard-table__cell">
                            {{ report.resolved_text }}
                        </td>
                        <td class="standard-table__cell">
                            {{ report.title|default:'---' }}
                        </td>
                        <td class="standard-table__cell">
                            {{ report.created_by.name|default:'---' }}
                        </td>
                        <td class="standard-table__cell">
                            <a class="table__link" href="{% url 'reports:report-barrier-drafts' report.id %}">Continue</a>
                            {% if report.created_by.id == current_user.id %}
                                <a class="table__link js-delete-modal" href="{% url 'reports:delete_report' report.id %}">Delete</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}

        <div class="no-results-box">
            <p>
                There are currently no draft market access barriers.
            </p>
        </div>

    {% endif %}
{% endblock %}

templates/users/account/edit_barrier_locations.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block body_script %}
    {{ block.super }}
    <script nonce="{{request.csp_nonce}}">
        ma.components.MultiSelect(element="barrier_locations_multiselect");
    </script>
{% endblock %}

{% block page_title %}{{ block.super }} - Account{% endblock %}
{% block masthead %}
    {% include 'users/partials/account/banner.html' with active="my profile" %}
{% endblock %}
{% block page_content %}
    <div class="govuk-summary-card">
        <div class="govuk-summary-card__title-wrapper">
            <h3 class="govuk-summary-card__title ">My role and areas of interest</h3>
        </div>
        <div id="barrier_locations_multiselect">{% include 'users/partials/account/multi_select.html' with form=form select_text="Select a barrier location" add_text="Add location" %}</div>
    </div>
{% endblock %}

templates/users/account/edit_government_department.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block page_title %}{{ block.super }} - Account{% endblock %}
{% block masthead %}
    {% include 'users/partials/account/banner.html' with active="my profile" %}
{% endblock %}
{% block page_content %}
    <div class="govuk-summary-card">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="govuk-summary-card__title-wrapper">
                <h3 class="govuk-summary-card__title ">My role and areas of interest</h3>
            </div>
            {% include 'users/partials/account/fieldset.html' with form=form select_text="Select a government department" select_options=form.fields.form.choices %}
            <div class="govuk-summary-card__content">
                <input type="submit" value="Save and return" class="govuk-button">
            </div>
        </form>
    </div>
{% endblock %}

templates/users/account/edit_overseas_regions.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block body_script %}
    {{ block.super }}
    <script nonce="{{request.csp_nonce}}">
        ma.components.MultiSelect(element="overseas_regions_multiselect");
    </script>
{% endblock %}

{% block page_title %}{{ block.super }} - Account{% endblock %}
{% block masthead %}
    {% include 'users/partials/account/banner.html' with active="my profile" %}
{% endblock %}
{% block page_content %}
    <div class="govuk-summary-card">
        <div class="govuk-summary-card__title-wrapper">
            <h3 class="govuk-summary-card__title ">My role and areas of interest</h3>
        </div>
        <div id="overseas_regions_multiselect">{% include 'users/partials/account/multi_select.html' with form=form select_text="Select an overseas region" add_text="Add region" %}</div>
    </div>
{% endblock %}

templates/users/account/saved_search.html
{% extends "base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% block page_title %}
    {{ block.super }} - Account
{% endblock page_title %}
{% block masthead %}
    {% include "users/partials/account/banner.html" with active=active %}
{% endblock masthead %}
{% block page_content %}
    <section>
        <h2 class="ma-list-heading">
            <span class="ma-list-heading__count">{{ saved_searches|length }}</span> saved search{{ saved_searches|length|pluralize:"es" }}
        </h2>
        <ul class="ma-card-list">
            {% for saved_search in saved_searches %}
                <li class="ma-card-list__item saved-search">
                    <div class="saved-search__content">
                        <h3 class="saved-search__title">
                            <a href="{% url 'barriers:search' %}?{{ saved_search.querystring }}&search_id={{ saved_search.id }}">{{ saved_search.name }}</a>
                        </h3>
                        {% include "barriers/partials/saved_search_badges.html" %}
                        {% if saved_search.filters %}
                            <ul class="saved-search__filter-list">
                                {% for name, value in saved_search.readable_filters.items %}
                                    <li class="saved-search__filter-list-item">{{ value.readable_value|striptags }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                    <a class="saved-search__notifications"
                       href="{% url 'barriers:saved_search_notifications' saved_search.id %}">Notifications: {{ saved_search.notifications_text }}</a>
                    <div class="saved-search__actions">
                        <a class="saved-search__action-item"
                           href="{% url 'barriers:rename_saved_search' saved_search.id %}">Rename</a>
                        <a class="saved-search__action-item"
                           href="{% url 'barriers:delete_saved_search' saved_search.id %}">Delete</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock page_content %}