barriers/urls.py
from django.urls import path, re_path

from barriers.views.action_plans import (
    ActionPlanMilestoneFormView,
    ActionPlanRisksAndMitigationView,
    ActionPlanStakeholdersListView,
    ActionPlanTaskCompletionDateChangeFormView,
    ActionPlanTaskFormView,
    ActionPlanTemplateView,
    AddActionPlanStrategicContext,
    CreateActionPlanStakeholderIndividualFormView,
    CreateActionPlanStakeholderOrganisationFormView,
    CreateActionPlanStakeholderTypeFormView,
    DeleteActionPlanMilestoneView,
    DeleteActionPlanTaskView,
    EditActionPlanCurrentStatusFormView,
    EditActionPlanOwner,
    EditActionPlanStakeholderDetailsFormView,
    EditActionPlanTaskOutcomeFormView,
    EditActionPlanTaskProgressFormView,
    RemoveActionPlanOwner,
    SelectActionPlanOwner,
)
from barriers.views.archive import ArchiveBarrier, UnarchiveBarrier
from barriers.views.assessments.economic import (
    AddEconomicAssessment,
    AddEconomicAssessmentDocument,
    ArchiveEconomicAssessment,
    AutomateEconomicAssessment,
    CancelEconomicAssessmentDocument,
    DeleteEconomicAssessmentDocument,
    EconomicAssessmentDetail,
    EconomicAssessmentRawData,
    EditEconomicAssessmentRating,
)
from barriers.views.assessments.economic_impact import (
    AddEconomicImpactAssessment,
    ArchiveEconomicImpactAssessment,
    EconomicImpactAssessmentDetail,
)
from barriers.views.assessments.overview import AssessmentOverview
from barriers.views.assessments.preliminary_assessment import PreliminaryAssessmentValue
from barriers.views.assessments.resolvability import (
    AddResolvabilityAssessment,
    ArchiveResolvabilityAssessment,
    EditResolvabilityAssessment,
    ResolvabilityAssessmentDetail,
)
from barriers.views.assessments.strategic import (
    AddStrategicAssessment,
    ArchiveStrategicAssessment,
    EditStrategicAssessment,
    StrategicAssessmentDetail,
)
from barriers.views.commodities import BarrierEditCommodities
from barriers.views.companies import (
    BarrierEditCompanies,
    BarrierEditCompaniesSession,
    BarrierRemoveCompany,
    CompanyDetail,
)
from barriers.views.documents import DownloadDocument
from barriers.views.edit import (
    BarrierEditCausedByTradingBloc,
    BarrierEditCommercialValue,
    BarrierEditEconomicAssessmentEligibility,
    BarrierEditEstimatedResolutionDateConfirmationPage,
    BarrierEditPriority,
    BarrierEditProduct,
    BarrierEditStartDate,
    BarrierEditSummary,
    BarrierEditTags,
    BarrierEditTitle,
    BarrierEditTradeDirection,
)
from barriers.views.export_types import BarrierEditExportType
from barriers.views.government_organisations import (
    BarrierAddGovernmentOrganisation,
    BarrierEditGovernmentOrganisations,
    BarrierRemoveGovernmentOrganisation,
)
from barriers.views.history import BarrierHistory
from barriers.views.location import (
    AddAdminArea,
    BarrierEditCountryOrTradingBloc,
    BarrierEditLocation,
    BarrierEditLocationSession,
    RemoveAdminArea,
)
from barriers.views.mentions import (
    MentionMarkAllAsRead,
    MentionMarkAllAsUnread,
    MentionMarkAsRead,
    MentionMarkAsReadAndRedirect,
    MentionMarkAsUnread,
    TurnNotificationsOffAndRedirect,
    TurnNotificationsOnAndRedirect,
)
from barriers.views.notes import (
    AddNoteDocument,
    BarrierAddNote,
    BarrierDeleteNote,
    BarrierEditNote,
    CancelNoteDocument,
    DeleteNoteDocument,
)
from barriers.views.policy_teams import (
    AddPolicyTeam,
    BarrierEditPolicyTeams,
    BarrierEditPolicyTeamsSession,
    BarrierRemovePolicyTeam,
)
from barriers.views.progress_updates import (
    BarrierAddProgrammeFundProgressUpdate,
    BarrierAddProgressUpdate,
    BarrierCompleteNextStepItem,
    BarrierEditNextStepItem,
    BarrierEditProgressUpdate,
    BarrierListNextStepsItems,
    BarrierListProgressUpdate,
    ChooseProgressUpdateTypeView,
    ProgrammeFundEditProgressUpdate,
    ProgrammeFundListProgressUpdate,
)
from barriers.views.public_barriers import (
    EditPublicEligibility,
    EditPublicSummary,
    EditPublicTitle,
    PublicBarrierApprovalConfirmation,
    PublicBarrierDetail,
    PublicBarrierListView,
    PublicBarrierPublishConfirmation,
    PublicBarrierUnpublishConfirmation,
)
from barriers.views.saved_searches import (
    DeleteSavedSearch,
    NewSavedSearch,
    RenameSavedSearch,
    SavedSearchNotifications,
)
from barriers.views.search import (
    BarrierDownloadLink,
    BarrierSearch,
    DownloadBarriers,
    DownloadBarriersDelete,
    DownloadBarriersDetail,
    RequestBarrierDownloadApproval,
)
from barriers.views.sectors import (
    BarrierAddAllSectors,
    BarrierAddMainSector,
    BarrierAddSectors,
    BarrierEditSectors,
    BarrierEditSectorsSession,
    BarrierRemoveSector,
)
from barriers.views.statuses import BarrierChangeStatus
from barriers.views.teams import (
    BarrierTeam,
    ChangeOwnerView,
    DeleteTeamMember,
    SearchTeamMember,
)
from barriers.views.wto import (
    AddWTODocument,
    CancelWTODocuments,
    DeleteWTODocument,
    EditWTOProfile,
    EditWTOStatus,
)

from .views.core import (
    BarrierDetail,
    Dashboard,
    GetDashboardSummary,
    Home,
    WhatIsABarrier,
)
from .views.estimated_resolution_date import AddEstimatedResolutionDateFormView, EditEstimatedResolutionDateFormView, \
    DeleteEstimatedResolutionDateFormView, ReviewEstimatedResolutionDateFormView, RejectEstimatedResolutionDateFormView, \
    ApproveEstimatedResolutionDateFormView, ConfirmationEstimatedResolutionDateFormView
from .views.related_barriers import RelatedBarriers

app_name = "barriers"

urlpatterns = [
    path("", Dashboard.as_view(), name="dashboard"),
    path("search/", BarrierSearch.as_view(), name="search"),
    path("find-a-barrier/", BarrierSearch.as_view(), name="find_a_barrier"),
    path("search/download/", DownloadBarriers.as_view(), name="download"),
    path(
        "search/download/<uuid:download_barrier_id>",
        DownloadBarriersDetail.as_view(),
        name="download-detail",
    ),
    path(
        "search/download/<uuid:download_barrier_id>/link/",
        BarrierDownloadLink.as_view(),
        name="download-link",
    ),
    path(
        "search/download/<uuid:download_barrier_id>/delete/",
        DownloadBarriersDelete.as_view(),
        name="delete-download",
    ),
    path(
        "search/request_download_approval/",
        RequestBarrierDownloadApproval.as_view(),
        name="request_download_approval",
    ),
    path("what-is-a-barrier/", WhatIsABarrier.as_view(), name="what_is_a_barrier"),
    path(
        "documents/<uuid:document_id>/download/",
        DownloadDocument.as_view(),
        name="download_document",
    ),
    path("saved-searches/new/", NewSavedSearch.as_view(), name="new_saved_search"),
    path(
        "saved-searches/<uuid:saved_search_id>/rename/",
        RenameSavedSearch.as_view(),
        name="rename_saved_search",
    ),
    path(
        "saved-searches/<uuid:saved_search_id>/delete/",
        DeleteSavedSearch.as_view(),
        name="delete_saved_search",
    ),
    path(
        "saved-searches/<uuid:saved_search_id>/notifications/",
        SavedSearchNotifications.as_view(),
        name="saved_search_notifications",
    ),
    re_path(
        "saved-searches/(?P<saved_search_id>(my|team)-barriers)/notifications/",
        SavedSearchNotifications.as_view(),
        name="saved_search_notifications",
    ),
    path("barriers/<uuid:barrier_id>/", BarrierDetail.as_view(), name="barrier_detail"),
    # Reason for double url: Analytics requested a second url pointing to the same page
    path(
        "barriers/<uuid:barrier_id>/complete/",
        BarrierDetail.as_view(),
        name="barrier_detail_from_complete",
    ),
    re_path(
        "barriers/(?P<barrier_id>[A-Z]-[0-9]{2}-[A-Z0-9]{3})/",
        BarrierDetail.as_view(),
        name="barrier_detail_by_code",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/title/",
        BarrierEditTitle.as_view(),
        name="edit_title",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/product/",
        BarrierEditProduct.as_view(),
        name="edit_product",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/summary/",
        BarrierEditSummary.as_view(),
        name="edit_summary",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/priority/",
        BarrierEditPriority.as_view(),
        name="edit_priority",
    ),
    path(
        "barriers/<uuid:barrier_id>/list/progress_update/",
        BarrierListProgressUpdate.as_view(),
        name="list_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/progress_update/<uuid:progress_update_id>/",
        BarrierEditProgressUpdate.as_view(),
        name="edit_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/list/programme_fund_progress_update/",
        ProgrammeFundListProgressUpdate.as_view(),
        name="list_barrier_fund_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/programme_fund_progress_update/<uuid:progress_update_id>/",
        ProgrammeFundEditProgressUpdate.as_view(),
        name="edit_barrier_fund_progress_update",
    ),
    path(
        "barriers/<uuid:barrier_id>/list/next_steps_items/",
        BarrierListNextStepsItems.as_view(),
        name="list_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/next_step_item_update/<uuid:item_id>/",
        BarrierEditNextStepItem.as_view(),
        name="edit_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/add/next_step_item_update/",
        BarrierEditNextStepItem.as_view(),
        name="add_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/next_step_item_complete/<uuid:item_id>/",
        BarrierCompleteNextStepItem.as_view(),
        name="complete_next_steps",
    ),
    path(
        "barriers/<uuid:barrier_id>/edit/economic-assessment-eligibility/",

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from pingdom.urls import urlpatterns as pingdom_urlpatterns

urlpatterns = []

if settings.DEBUG and settings.DJANGO_ENV == "local":
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("", include("users.urls", namespace="users")),
    path("", include("barriers.urls", namespace="barriers")),
    path("", include("reports.urls", namespace="reports")),
    path("", include("core.urls", namespace="core")),
    path("", include("healthcheck.urls", namespace="healthcheck")),
] + pingdom_urlpatterns

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from barriers.views.feedback import FeedbackFormView, FeedbackGratitudeView
from utils.company_search import SearchCompany

app_name = "core"

urlpatterns = [
    path(
        "accessibility/",
        TemplateView.as_view(template_name="accessibility.html"),
        name="accessibility",
    ),
    path(
        "feedback/",
        FeedbackFormView.as_view(),
        name="feedback",
    ),
    path(
        "feedback/thankyou/",
        FeedbackGratitudeView.as_view(),
        name="feedback-thanks",
    ),
    path(
        "companies/search/<str:search_term>/",
        SearchCompany.as_view(),
        name="search_company",
    ),
]

users/urls.py
from django.urls import path

from users.account.views import (
    UserEditBarrierLocations,
    UserEditGovernmentDepartment,
    UserEditOverseasRegions,
    UserEditPolicyTeams,
    UserEditSectors,
)
from users.views import (
    Account,
    AccountDownloads,
    AccountDrafts,
    AccountSavedSearch,
    AddUser,
    DeleteUser,
    EditUser,
    ExportUsers,
    GetUsers,
    Login,
    LoginCallback,
    ManageUsers,
    Mentions,
    SignOut,
    UserDetail,
)

app_name = "users"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("login/callback/", LoginCallback.as_view(), name="login_callback"),
    path("sign-out/", SignOut.as_view(), name="sign-out"),
    path("users/", ManageUsers.as_view(), name="manage_users"),
    path("users/search/", GetUsers.as_view(), name="get_users"),
    path("users/export/", ExportUsers.as_view(), name="export_users"),
    path("users/add/", AddUser.as_view(), name="add_user"),
    path("users/<int:user_id>/", UserDetail.as_view(), name="user_detail"),
    path("users/<int:user_id>/edit/", EditUser.as_view(), name="edit_user"),
    path("users/<int:user_id>/delete/", DeleteUser.as_view(), name="delete_user"),
    path("account/", Account.as_view(), name="account"),
    path(
        "account/saved_searches/",
        AccountSavedSearch.as_view(),
        name="account_saved_searches",
    ),
    path(
        "account/downloads/",
        AccountDownloads.as_view(),
        name="account_downloads",
    ),
    path(
        "account/drafts/",
        AccountDrafts.as_view(),
        name="account_drafts",
    ),
    path(
        "account/policy-teams/edit/",
        UserEditPolicyTeams.as_view(),
        name="edit_user_policy_teams",
    ),
    path(
        "account/sectors/edit/",
        UserEditSectors.as_view(),
        name="edit_user_sectors",
    ),
    path(
        "account/barrier-locations/edit/",
        UserEditBarrierLocations.as_view(),
        name="edit_user_barrier_locations",
    ),
    path(
        "account/overseas-regions/edit/",
        UserEditOverseasRegions.as_view(),
        name="edit_user_overseas_regions",
    ),
    path(
        "account/government-department/edit/",
        UserEditGovernmentDepartment.as_view(),
        name="edit_user_government_department",
    ),
    path("mentions/", Mentions.as_view(), name="mentions"),
]

barriers/models/feedback.py
from utils.models import APIModel


class Feedback(APIModel):
    pass

barriers/forms/archive.py
from django import forms
from django.template.loader import render_to_string

from barriers.constants import ARCHIVED_REASON
from utils.api.client import MarketAccessAPIClient
from utils.forms import SubformChoiceField, SubformMixin


class DuplicateBarrierForm(forms.Form):
    duplicate_explanation = forms.CharField(
        label="Provide a reason",
        widget=forms.Textarea,
        max_length=1000,
        required=True,
        error_messages={
            "max_length": "Reason should be %(limit_value)d characters or less",
            "required": "Enter a reason",
        },
    )

    def get_explanation(self):
        return self.cleaned_data["duplicate_explanation"]

    def as_html(self):
        template_name = "barriers/forms/archive/duplicate.html"
        return render_to_string(template_name, context={"form": self})


class NotABarrierForm(forms.Form):
    not_a_barrier_explanation = forms.CharField(
        label="Provide a reason",
        widget=forms.Textarea,
        max_length=1000,
        required=True,
        error_messages={
            "max_length": "Reason should be %(limit_value)d characters or less",
            "required": "Enter a reason",
        },
    )

    def get_explanation(self):
        return self.cleaned_data["not_a_barrier_explanation"]

    def as_html(self):
        template_name = "barriers/forms/archive/not_a_barrier.html"
        return render_to_string(template_name, context={"form": self})


class OtherForm(forms.Form):
    other_explanation = forms.CharField(
        label="Provide a reason",
        widget=forms.Textarea,
        max_length=1000,
        required=True,
        error_messages={
            "max_length": "Reason should be %(limit_value)d characters or less",
            "required": "Enter a reason",
        },
    )

    def get_explanation(self):
        return self.cleaned_data["other_explanation"]

    def as_html(self):
        template_name = "barriers/forms/archive/other.html"
        return render_to_string(template_name, context={"form": self})


class ArchiveBarrierForm(SubformMixin, forms.Form):
    reason = SubformChoiceField(
        label="Why are you archiving this barrier?",
        help_text=(
            "You can find archived barriers in search by "
            "selecting the 'Show' filter 'Only archived barriers'."
        ),
        choices=ARCHIVED_REASON,
        subform_classes={
            ARCHIVED_REASON.DUPLICATE: DuplicateBarrierForm,
            ARCHIVED_REASON.NOT_A_BARRIER: NotABarrierForm,
            ARCHIVED_REASON.OTHER: OtherForm,
        },
        widget=forms.RadioSelect,
        error_messages={"required": "Select duplicate, not a barrier or other"},
    )

    def __init__(self, id, token, *args, **kwargs):
        self.barrier_id = id
        self.token = token
        super().__init__(*args, **kwargs)

    def save(self):
        client = MarketAccessAPIClient(self.token)
        client.barriers.patch(
            id=self.barrier_id,
            archived=True,
            archived_reason=self.cleaned_data.get("reason"),
            archived_explanation=self.fields["reason"].subform.get_explanation(),
        )


class UnarchiveBarrierForm(forms.Form):
    reason = forms.CharField(
        label="Why are you unarchiving this barrier?",
        widget=forms.Textarea,
        max_length=1000,
        required=True,
        error_messages={
            "max_length": "Reason should be %(limit_value)d characters or less",
            "required": "Enter a reason",
        },
    )

    def __init__(self, id, token, *args, **kwargs):
        self.barrier_id = id
        self.token = token
        super().__init__(*args, **kwargs)

    def save(self):
        client = MarketAccessAPIClient(self.token)
        client.barriers.patch(
            id=self.barrier_id,
            archived=False,
            unarchived_reason=self.cleaned_data.get("reason"),
        )

templates/barriers/delete_note.html
{% extends 'barriers/barrier_detail.html' %}

{% block outside_content %}
    {% include 'barriers/modals/delete_note.html' %}
{% endblock %}

templates/barriers/find_a_barrier.html
{% extends 'base.html' %}

{% load static %}

{% block page_title %}{{ block.super }} - Find a barrier{% endblock %}

{% block body_script %}
    <script src="{% static 'js/vue/vue-bundle.js' %}"></script>
{% endblock %}

{% block page_content %}

    {% include 'partials/heading.html' with caption='Market access barriers' text='Find a barrier' %}

    <section class="govuk-grid-row">
        <div class="govuk-grid-column-one-quarter">
            <h2 class="filter-list-title">Filter barriers by:</h2>
            <form action="" method="GET" class="filter-items">

                {% if form.search_id.value %}{{ form.search_id }}{% endif %}

                <div id="{{ form.search.name }}" class="govuk-form-group filter-items-group">
                    <label class="govuk-label filter-items__label" for="search">
                      {{ form.search.label }}
                    </label>

                    <input class="govuk-input" name="search" type="text" value="{% if form.search.value %}{{ form.search.value }}{% endif %}">
                </div>

                {% include "partials/forms/search_typeahead.html" with placeholder='Search locations' field=form.country %}
                {% include "partials/forms/checkbox_filter.html" with field=form.trade_direction %}
                {% include "partials/forms/search_typeahead.html" with placeholder='Search sector' field=form.sector %}
                {% include "partials/forms/search_typeahead.html" with placeholder='Search type' field=form.type %}
                {% include "partials/forms/search_typeahead.html" with placeholder='Search regions' field=form.region extra_classes='js-filter' %}
                {% include 'partials/forms/checkbox_filter.html' with field=form.priority extra_classes='barrier-priority-filter' %}
                {% include 'partials/forms/checkbox_filter.html' with field=form.status %}

                {% include 'partials/forms/checkbox_filter.html' with field=form.wto %}

                {% include 'partials/forms/checkbox_filter.html' with field=form.tags %}

                <div id="show" class="govuk-form-group filter-group">
                    <fieldset class="govuk-fieldset filter-group__inner">
                        <legend class="govuk-fieldset__legend filter-items__label filter-group__label">Show</legend>

                        <div class="checkbox-filter govuk-!-width-full">
                            {% include 'partials/forms/checkbox.html' with field=form.user %}
                            {% include 'partials/forms/checkbox.html' with field=form.team %}
                            {% include 'partials/forms/checkbox.html' with field=form.only_archived %}
                        </div>
                    </fieldset>
                </div>

                {% if filters %}
                <a class="filter-items__clear" href="{% url 'barriers:find_a_barrier' %}">Remove all filters</a>
                {% endif %}

                <input type="submit" value="Apply filters" class="govuk-button govuk-button--full-width js-filter-submit">
            </form>
        </div>
        <div class="govuk-grid-column-three-quarters">

            <div class="filter-results-header">
                {% if saved_search %}
                    <h2 class="search-title">{{ saved_search.name }}</h2>
                {% elif search_title %}
                    <h2 class="search-title">{{ search_title }}</h2>
                {% elif member %}
                    <h2 class="search-title">{{ member.user.full_name }}</h2>
                {% endif %}

                {% if filters %}
                    <div class="filter-results-header__row">
                        {% if have_filters_changed %}
                            <div class="filter-results-header__row-item">
                                <p class="filter-results-header__info">You have unsaved changes.</p>
                            </div>
                        {% endif %}

                        {% if saved_search_updated or saved_search_created %}
                            <div class="filter-results-header__row-item">
                                <p class="filter-results-header__info">Your search has been successfully saved.</p>
                            </div>
                        {% endif %}

                        <div class="filter-results-header__row-item filter-results-header__row-item--right">
                            {% if form.search_id.value is not None %}
                                {% if have_filters_changed %}
                                    <form class="filter-results-header__update_form" method="post">
                                        {% csrf_token %}
                                        <button class="govuk-button button-as-link filter-results-header__update-button" name="update_search" value="1">Update saved search</button>
                                    </form>
                                    <a href="{% url 'barriers:new_saved_search' %}?{{ pageless_querystring }}" class="govuk-button filter-results-header__save-button">Save as new search</a>
                                {% endif %}
                            {% elif filters and not search_title %}
                                <a href="{% url 'barriers:new_saved_search' %}?{{ pageless_querystring }}" class="govuk-button filter-results-header__save-button">Save as new search</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                <div class="filter-results-header__row">
                    <h2 class="filter-results-title filter-results-header__row-item">{{ barriers.total_count }}<span class="filter-results-title__caption"> barrier{{ barriers.total_count|pluralize }}</span></h2>

                    <div class="filter-results-header__row-item">
                        {% if form.search_id.value is not None %}
                            <a class="" href="">Notifications: off</a>
                        {% endif %}

                        {% if filters %}
                            <a class="filter-results-clear-link" href="{% url 'barriers:find_a_barrier' %}{% if request.GET.edit %}?edit={{ request.GET.edit }}{% endif %}">Remove all filters</a>
                        {% endif %}
                    </div>
                </div>

                {% if filters %}
                    <h3 class="visually-hidden">Active filters:</h3>
                    <ul class="active-filters">
                        {% include 'barriers/partials/active_filter.html' with filter=filters.member %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.country %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.trade_direction %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.sector %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.type %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.search %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.region %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.priority %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.status %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.wto %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.tags %}
                        {% include 'barriers/partials/active_filter.html' with filter=filters.show %}
                    </ul>
                {% endif %}
            </div>

            {% if pagination.total_pages > 1 %}
            <p class="filter-results-pagination-summary">
                Page {{ pagination.current_page }} of {{ pagination.total_pages }}
            </p>
            {% endif %}

            <p class="filter-results-download">
                {% if barriers %}
                    <span class="filter-results-download__text">
                    {% if barriers.total_count == 1 %}
                        You can download this barrier
                    {% else %}
                        You can download these {{ barriers.total_count }} barriers
                    {% endif %}
                    </span>
                    <a class="govuk-button filter-results-download__button" href="{% url 'barriers:download' %}{% if request.GET %}?{{ pageless_querystring }}{% endif %}">Download</a>
                {% else %}
                    <span class="filter-results-download__text">There are no barriers to download</span>
                {% endif %}
            </p>

            <ol class="filter-results-list">
                {% for barrier in barriers %}
                    <li class='filter-results-list__item' data-barrier-id="{{ barrier.id }}">
                        <div class="filter-results-list__item__main-content">
                            {% if barrier.archived %}
                                <div class="govuk-warning-text govuk-!-margin-bottom-2">
                                    <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
                                    <strong class="govuk-warning-text__text">
                                        <span class="govuk-warning-text__assistive">Warning</span>
                                        This barrier was archived on {{ barrier.archived_on|date:"j F Y" }}
                                    </strong>
                                </div>
                            {% endif %}
                            <h3 class='filter-results-list__item__heading'>
                                {% if saved_search %}
                                    {% if barrier.id in saved_search.new_barrier_ids %}
                                        <span class="ma-badge ma-badge--new">New</span>
                                    {% endif %}
                                    {% if barrier.id in saved_search.updated_barrier_ids %}
                                        <span class="ma-badge ma-badge--updated">Updated</span>
                                    {% endif %}
                                {% endif %}
                                <a href="{% url 'barriers:barrier_detail' barrier.id %}">{{ barrier.title }}</a>
                            </h3>
                            <dl class="filter-results-list__item__definitions">

                                <dt class="filter-results-list__item__definitions__key visually-hidden">ID:</dt>
                                <dd class="filter-results-list__item__definitions__value">{{ barrier.code }}</dd>

                                <dt class="filter-results-list__item__definitions__key">Reported:</dt>

                                <dd class="filter-results-list__item__definitions__value">{{ barrier.reported_on|date:"j F Y" }}</dd>

                                {% if barrier.sectors %}
                                <dt class="filter-results-list__item__definitions__key">Sector{{ barrier.sectors|pluralize }} affected:</dt>
                                <dd class="filter-results-list__item__definitions__value">{{ barrier.sector_names|join:', ' }}</dd>
                                {% endif %}

                                <dt class="filter-results-list__item__definitions__key">Barrier location:</dt>
                                <dd class="filter-results-list__item__definitions__value">{{ barrier.location }}</dd>
                            </dl>
                        </div>

                        <div class="filter-results-list__item__sub-content">
                            <div class="barrier-status-badge barrier-status-badge--compact barrier-status-badge--{{ barrier.status.modifier }}">
                                <strong>{{ barrier.status.name }}</strong>
                                <div class="priority-marker-wrapper">
                                    <span class="priority-marker priority-marker--{{ barrier.priority.code|lower }}"></span><strong>{{ barrier.priority.name }}</strong> priority
                                </div>
                            </div>

                            {% if barrier.tags %}
                                <ul class="barrier-tag-list">
                                    {% spaceless %}
                                        {% for tag in barrier.tags %}
                                        <li class="barrier-tag-list__tag">{{ tag.title }}</li>
                                        {% endfor %}
                                    {% endspaceless %}
                                </ul>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ol>

            {% include 'partials/pagination.html' %}

        </div>
    </section>

{% endblock %}